/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedYearlyRouteImport } from './routes/_authenticated/yearly'
import { Route as AuthenticatedWeeklyRouteImport } from './routes/_authenticated/weekly'
import { Route as AuthenticatedTrackerRouteImport } from './routes/_authenticated/tracker'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedRemindersRouteImport } from './routes/_authenticated/reminders'
import { Route as AuthenticatedMonthlyRouteImport } from './routes/_authenticated/monthly'
import { Route as AuthenticatedHabitsRouteImport } from './routes/_authenticated/habits'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/coach'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedYearlyRoute = AuthenticatedYearlyRouteImport.update({
  id: '/yearly',
  path: '/yearly',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWeeklyRoute = AuthenticatedWeeklyRouteImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrackerRoute = AuthenticatedTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRemindersRoute = AuthenticatedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonthlyRoute = AuthenticatedMonthlyRouteImport.update({
  id: '/monthly',
  path: '/monthly',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHabitsRoute = AuthenticatedHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/monthly': typeof AuthenticatedMonthlyRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tracker': typeof AuthenticatedTrackerRoute
  '/weekly': typeof AuthenticatedWeeklyRoute
  '/yearly': typeof AuthenticatedYearlyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/monthly': typeof AuthenticatedMonthlyRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tracker': typeof AuthenticatedTrackerRoute
  '/weekly': typeof AuthenticatedWeeklyRoute
  '/yearly': typeof AuthenticatedYearlyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/coach': typeof AuthenticatedCoachRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/habits': typeof AuthenticatedHabitsRoute
  '/_authenticated/monthly': typeof AuthenticatedMonthlyRoute
  '/_authenticated/reminders': typeof AuthenticatedRemindersRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tracker': typeof AuthenticatedTrackerRoute
  '/_authenticated/weekly': typeof AuthenticatedWeeklyRoute
  '/_authenticated/yearly': typeof AuthenticatedYearlyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/achievements'
    | '/analytics'
    | '/calendar'
    | '/coach'
    | '/dashboard'
    | '/goals'
    | '/habits'
    | '/monthly'
    | '/reminders'
    | '/schedule'
    | '/settings'
    | '/tracker'
    | '/weekly'
    | '/yearly'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/achievements'
    | '/analytics'
    | '/calendar'
    | '/coach'
    | '/dashboard'
    | '/goals'
    | '/habits'
    | '/monthly'
    | '/reminders'
    | '/schedule'
    | '/settings'
    | '/tracker'
    | '/weekly'
    | '/yearly'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/achievements'
    | '/_authenticated/analytics'
    | '/_authenticated/calendar'
    | '/_authenticated/coach'
    | '/_authenticated/dashboard'
    | '/_authenticated/goals'
    | '/_authenticated/habits'
    | '/_authenticated/monthly'
    | '/_authenticated/reminders'
    | '/_authenticated/schedule'
    | '/_authenticated/settings'
    | '/_authenticated/tracker'
    | '/_authenticated/weekly'
    | '/_authenticated/yearly'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/yearly': {
      id: '/_authenticated/yearly'
      path: '/yearly'
      fullPath: '/yearly'
      preLoaderRoute: typeof AuthenticatedYearlyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/weekly': {
      id: '/_authenticated/weekly'
      path: '/weekly'
      fullPath: '/weekly'
      preLoaderRoute: typeof AuthenticatedWeeklyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tracker': {
      id: '/_authenticated/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof AuthenticatedTrackerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reminders': {
      id: '/_authenticated/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AuthenticatedRemindersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monthly': {
      id: '/_authenticated/monthly'
      path: '/monthly'
      fullPath: '/monthly'
      preLoaderRoute: typeof AuthenticatedMonthlyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/habits': {
      id: '/_authenticated/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AuthenticatedHabitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedHabitsRoute: typeof AuthenticatedHabitsRoute
  AuthenticatedMonthlyRoute: typeof AuthenticatedMonthlyRoute
  AuthenticatedRemindersRoute: typeof AuthenticatedRemindersRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTrackerRoute: typeof AuthenticatedTrackerRoute
  AuthenticatedWeeklyRoute: typeof AuthenticatedWeeklyRoute
  AuthenticatedYearlyRoute: typeof AuthenticatedYearlyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCoachRoute: AuthenticatedCoachRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedHabitsRoute: AuthenticatedHabitsRoute,
  AuthenticatedMonthlyRoute: AuthenticatedMonthlyRoute,
  AuthenticatedRemindersRoute: AuthenticatedRemindersRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTrackerRoute: AuthenticatedTrackerRoute,
  AuthenticatedWeeklyRoute: AuthenticatedWeeklyRoute,
  AuthenticatedYearlyRoute: AuthenticatedYearlyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
